# This file controls the configuration for your local development stack
# For a reference of all options, see https://supabase.com/docs/guides/cli/config

[api]
port = 54341
schemas = ["public", "storage", "auth"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54343
shadow_port = 54320
major_version = 15

[studio]
port = 54324

[inbucket]
port = 54325
smtp_port = 54326
pop3_port = 54327

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[realtime]
enabled = true
ip_version = "IPv4"

[storage]
file_size_limit = 52428800

[analytics]
enabled = false